title: Pagina de status dos serviços da RNP
languageCode: pt_BR
params:
  copyrightHolder: RNP
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: ''
  description_header: ''
  eventsPerPage: 10
  groups:
    - Serviços
  logo: /images/clearstatus.svg
  meta_description: >-
    Esta pagina tem como objetivo apresentar o status dos principais serviços da
    RNP.
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: Site Publico da RNP
      link: 'https://www.rnp.br/'
      name: Site Publico
    - description: Atendimento e Suporte da RNP
      link: 'https://atendimento.rnp.br/'
      name: Service Desk
  timezoneString: ' America/Sao_Paulo'
