title: Pagina de status dos serviços da RNP
languageCode: en
params:
  copyrightHolder: RNP
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>Example.com</a> provides open-source
    software for all kind of sectors.
  description_header: >-
    Information about <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>example</a> systems operations.<br />Follow
    us <a class='text-grey-darkest' title='Visit our page on Twitter'
    href='https://www.twitter.com/example'>on Twitter</a> or subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  eventsPerPage: 10
  groups:
    - Serviços
  logo: /images/clearstatus.svg
  meta_description: >-
    Esta pagina tem como objetivo apresentar o status dos principais serviços da
    RNP.
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: Site Publico da RNP
      link: 'https://www.rnp.br/'
      name: Site Publico
    - description: Atendimento e Suporte da RNP
      link: 'https://atendimento.rnp.br/'
      name: Service Desk
  timezoneString: ' America/Sao_Paulo'
